---
- name: Unmount the device if already mounted
  ansible.builtin.command:
    cmd: umount /dev/sdb1
  ignore_errors: true
  become: true

- name: Mount the external hard drive
  ansible.builtin.command:
    cmd: mount /dev/sdb1 /media/toshiba-ext-hdd
  become: true

- name: ensure the transmission network exists
  docker_network:
    name: transmission

- name: copy the shell script which starts the docker container to the target machine
  copy:
    src: ./check_and_run_docker.sh
    dest: /tmp/check_and_run_docker.sh
    mode: '0755'

- name: execute the shell script
  shell: /tmp/check_and_run_docker.sh {{ container_name }} {{ openvpn_provider }} {{ openvpn_config }} {{ openvpn_username }} {{ openvpn_password }} {{ local_network }}
  register: result
  ignore_errors: false

- name: remove the shell script after execution
  file:
    path: /tmp/check_and_run_docker.sh
    state: absent
