apiVersion: v1
kind: Secret
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:YzL2tsGBmv8=,iv:t1GIFbca+dqxcpgzeAWGXt4qyHqlXN3nSchboDWdr/E=,tag:YOob1YmVC/CxjxmA1SAMmQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:Eid9a3eiEa2OfbeArZgK6Cm3sjKb/a8xw1MNRiBABlmNr0OfWVxtDA==,iv:1I3CP+huUxhnlcciVr/u21hphuDt2IsCqw22uX2R3Eo=,tag:unmTDZ5RQTX+/fS7a/YTmw==,type:str]
metadata:
    name: linkding-secrets
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMTJLRDIrTmJvYWs5OVNy
            c0NTRnlqWC9LbUdWNXNBTTFDUy82NDZIUVFVCjhHcXpRYm1UVTByYkZBeEFQbmhn
            V1BjcG52RDIvSytHd2lxWUs0MGlvK3MKLS0tIFVkZVBlbmFzNy9ZTUorZGNLQ2Qr
            cGtCVzBjSytsQlVadURtbXRGQTd6R0EK4hqANO4uY1xDjr5URbyhBakaKfQ1K5dC
            nHRDUmUVmpWAfJoSRPvDEtOwxowlTXpo+LP+V0ShgMDzFwnR4GTeAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age190trgt6thma7h25pvh3z23pajxxq83rpg3x5y2pvlwa9hwhxpvmsapmcvs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T11:51:17Z"
    mac: ENC[AES256_GCM,data:qAc27R3uYeVaYGFRCavnDisc0j1t7Vrd9zupj6RKLVws32mfKM+GbMFh0iqOeAaWMZsfXAi4vDcpZRIr/2wej5U/BbpDAGBXg9h8FqHwvAL60u3wzUDY/72JrjYcnbCQvZs4LvpZ5jLp/Eh4Y/O7A40RlItBIFRj7nZdyN8A8X4=,iv:CWinBeWxW+WHuHTzyIrOvVNCPc8N+qW4fFK1bb8G7UU=,tag:kIMnFC1o7hqhmQC/SxBtVQ==,type:str]
    version: 3.13.3
