apiVersion: v1
kind: Secret
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:LJ7CDOyo4dk=,iv:TTSG98o91iAjEQ7K5zmi3B6xedL9wCPXZ9bZrzH3ayg=,tag:XsN3ooWO3GAL3yEmpMdBNA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:dIDwxgAiLn93Vqc0jdGCuFyS+duurPgWPPzgo2TAwSp/XdKDJH/K1kTd76E=,iv:VBjXjS3dzFrvX0hTWRN2qkZVqh1TyJz9UmPRhW+G7gk=,tag:zZFGaFCaFQzYf1g4A77uRw==,type:str]
metadata:
    name: linkding-secrets
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWXF1bjhSa3FrWWhrWnp3
            QUF6SERJeWlzRFFYbGtIcXlmdy8wRE4rOVVFCktXR3BySjkyN2QxT2hOVmNxMnZN
            QlFwRWZHVTlnRDhpTkd2bmVwRDVsdE0KLS0tIHphNmlKaWFLQllvcnYxdDFWQzNw
            RFJsMzB4LzczTDVOMmJIV1kzdFJIK2sKvh85qD82lqJCXXaOPoemFUhrOZxzXUmg
            XFMeqfh93pwU+4ExR64chJrK0aUVRBC9pcUHOTizx1OseV77aAFIEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age190trgt6thma7h25pvh3z23pajxxq83rpg3x5y2pvlwa9hwhxpvmsapmcvs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T11:15:15Z"
    mac: ENC[AES256_GCM,data:yPXmO74lYiDUaHHlsr/25WmHO0I84TCd969PJUzOOsVUN6ewl7JoGDOXBrkccGOdxONCmZWMKvNcDtxqRmFHilbrFxPAMz1zzXS/iiJfaHVVg/ErBhX9HodrPfyo3MGulXCuz71j+Il4lGXiOANsVYT2nqJzUqmOTU5HnskwovY=,iv:eZFrCqyzfSEBYxqkWgRtdwT11TRZCjprNsSXA/xWSR4=,tag:b/p6XFsa2y6kljCaeZ6IMg==,type:str]
    version: 3.13.3
