apiVersion: v1
kind: Secret
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:tRH0/g==,iv:4kY94zGXCisCknF6/4OJAxISzTKH/WCrUSfQyaqqq+Q=,tag:0EJEGr98SVz/093n25OcuA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:rbcIa9gAKL3/RPZed8NydBxkxCOC7flCls3RHpRs,iv:9AKlzLCnX739PEUSxWcXvTMrVWph2QO+3cdiF3Zs0cw=,tag:2I4HWz1SEMoYxRPYWMguuw==,type:str]
metadata:
    name: linkding-secrets
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWG9oSU9xM0M5NU5mYjhN
            MHFYWVJxUlQ1aDFlUkozbEFjSVpkQVNhTkFZCnQ4STFqNE1NbHVJZWJ6cnhKcXYx
            Nk9QYld2QitRM2oxaEpDcDRUS2x2LzgKLS0tIExqRWlKVWhmSHpXR3VVQkdpbjV4
            Y1hYOUNhcDcyb2IyNml1bnJMYUZOWkEK/H31/kbKILTBByVUEbpQ7YBztcWltQut
            Ge8f+0qhHsytVmw+F4beoPphqgFUwPN6HYDKbJdDla3QnjbCfmOOgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age190trgt6thma7h25pvh3z23pajxxq83rpg3x5y2pvlwa9hwhxpvmsapmcvs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T12:54:38Z"
    mac: ENC[AES256_GCM,data:GefcsFqNZM2RG3fS5QHPLcyHYLoMmZV5v2GWkCSrQbgBWeMGFy8y6M7mJg4w9fXG+R9ZyBj/HRCnD3lNetS5LcHsJAnSh12iAkHphJmz0LBkNPtUzqvzcNhBRhpMENh3dUaPBySbJdFqXdXQPg8M8sZJMGGNf6hhJa7O+eBTMGw=,iv:LXNUY8VJQuUxTM9bJiIj6LyyLylszHPvECRlN74ueH0=,tag:8hzJpf9eV0cTvaNp99L/WA==,type:str]
    version: 3.13.3
