apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ZFS4TiW145eLMtOsUGo1hy5mcsF+7v35hzlrRU+omJc+2m9IntaQjsByRxXZV+4BTC6UYqY5gXb45J9IkUf8Ljqd7P4lypdcab2ERSpwG0OhgAGtWrtHGK/Fw82G/pbR9BjyRG2SOlzoenPK6GtK7QDouihq1xCTcKiQWhyEMeu+TbCXFxP/u+XR7YeqwJ40l4cbKK2gjYcwzT/kRxQSWglGOSGs8TUlFsDzJktb07kJ1eQ5/PSiMuWNPpHlUNDJSwQws4OdhyhtNoq+QrvO/lJwjkGFSd0m,iv:i2lFMvlNxuPKQV1XIef02i3HwNi1BlQM0kjXHnKyhFI=,tag:mvg5YWuLSyLU6YDN1FcIwQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQXZEbWJpNWpJZmVYYjhr
            SmhJNnRucVg3Zit0VS9aN1VpOTNDZ0xCMlhvCncrZzdTTW4xRFRiVlhPWVhJRXJY
            UjlrbDkrdjdmMHdNc21aaHljZEVEblUKLS0tIHpXeEwwTXlpbDMzcXk4clI4eGd3
            b1drakdDNlJJY2cyaVc1ZkRLeUk4YmsKv6HBfxkdT7uvu12R67uyqVxAWwRbfFjg
            tHyfs1HIeP55mDb02IZwwQoBIidc2Og7iFSkN126dQkPTjTJfF+q/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age190trgt6thma7h25pvh3z23pajxxq83rpg3x5y2pvlwa9hwhxpvmsapmcvs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T12:49:47Z"
    mac: ENC[AES256_GCM,data:O+KAQqYWXykhJP6JM37anXwLxqCxbWk73/RgnVI0NbukPm5uQ/XCRCMLIhSuqySNfZBJzC4Hui2E+RjE5jCCA0YXWHMbLugE2/vfmNOEqTx6T6KAUn1AuuxAvqsCcb+rn8kkaRoNxtxEwr9gzrmt1/cZ7YFo3oeFYZIsur3+/2g=,iv:reztm0BuDGlBN8eQ3M98hJVmZ6vUBDkZO6bsbsw7fzU=,tag:vYE6x2f3Kmrxt4rryT5a3A==,type:str]
    version: 3.13.3
