#!/bin/bash
# set -e
# mise trust ./mise.toml
# if [ -f ./mise.local.toml ]; then
#     mise trust ./mise.local.toml
# fi
# mise install

/usr/local/bin/mise trust /workspaces/$DEVPOD_WORKSPACE_ID/mise.toml
if [ -f ./mise.local.toml ]; then
    mise trust ./mise.local.toml
fi
/usr/local/bin/mise install
