apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkding-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: linkding-pvc
    namespace: linkding
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-pvc
  namespace: linkding
spec:
  storageClassName: ""
  volumeName: linkding-pv
